// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvyxqskzozbitjusthng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2eXhxc2t6b3piaXRqdXN0aG5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Mzg5MzgsImV4cCI6MjA3MzAxNDkzOH0.kOesR10mJi9kgwfqN2djJcXNFRn8TODqWZETEdlt4tQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});